volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: "bridge"

services:
  prometheus:
    container_name: "prometheus"
    networks:
      - monitoring
    image: prom/prometheus
    command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/var/lib/prometheus"
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '800m'


  node_exporter:
    container_name: "node_exporter"
    networks:
      - monitoring
    image: prom/node-exporter
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: '250m'

  grafana:
    container_name: "grafana"
    networks:
      - monitoring
    image: grafana/grafana
    volumes:
      - "grafana_data:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - "prometheus"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '800m'
