global:
  scrape_interval: 10s
  evaluation_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "quarkus-bitcoin"
    metrics_path: "/q/metrics"
    static_configs:
      - targets: [ "host.docker.internal:8080" ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node_exporter:9100" ]




