{
 "title": "Quarkus Bitcoin",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "𝙏𝙍𝘼𝙉𝙎𝘼𝘾𝙏𝙄𝙊𝙉𝙎", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "𝙏𝙍𝘼𝙉𝙎𝘼𝘾𝙏𝙄𝙊𝙉𝙎 𝙈𝘼𝘿𝙀",
   "type": "barchart",
   "description": "Transactions made",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "application_transactions_current_total_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "𝘽𝙄𝘾𝙏𝙊𝙄𝙉 𝘾𝙐𝙍𝙍𝙀𝙉𝙏 𝙑𝘼𝙇𝙐𝙀",
   "type": "gauge",
   "description": "Current bitcoin value",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_bitcoins_current_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "𝙐𝙎𝙀𝙍𝙎 𝙊𝙉𝙇𝙄𝙉𝙀",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_auth_count_current_users_online",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "𝙈𝙀𝙈𝙊𝙍𝙔 𝙐𝙎𝘼𝙂𝙀",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}